# Introducción a NumPy

NumPy es una biblioteca usada para computación científica en Python.
Proporciona soporte para arrays y matrices grandes y multidimensionales, junto con una colección de funciones matemáticas de alto nivel.


In [ ]:
import numpy as np

### Creación de arrays


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
print("Array 1D:", arr1)

In [ ]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Array 2D:\n", arr2)

### Arrays especiales

In [ ]:
zeros = np.zeros((3, 3))
print("Array de ceros:\n", zeros)

In [ ]:
ones = np.ones((2, 4))
print("Array de unos:\n", ones)

In [ ]:
identity = np.eye(3)
print("Matriz identidad:\n", identity)

### Operaciones básicas

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Suma:", a + b)
print("Multiplicación elemento a elemento:", a * b)


### Indexación y slicing

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Elemento en índice 4:", arr[4])
print("Slice [3:7]:", arr[3:7])


In [ ]:
arr[4]=7
print("Elemento en índice 4:", arr[4])

arr[6:8] = 2
print("El valor del array es", arr)


### Funciones matemáticas

In [ ]:
x = np.array([0, np.pi/2, np.pi])
print("Seno de [0, pi/2, pi]:", np.sin(x))

### Estadísticas básicas



\\[
\bar{X} = \frac{1}{n} \sum_{i=1}^{n} X_i
\quad \quad \quad \quad \quad
\text{Var}(X) = \frac{1}{n} \sum_{i=1}^{n} (X_i - \bar{X})^2
\\]


In [ ]:
data = np.array([1, 2, 3, 4, 5])
print("Media:", np.mean(data))
print("Desviación estándar:", np.std(data))


Cálculo de la covarianza (por defecto usa estimador sesgado, se puede modificar usando el parametro ddof)
\\[
\text{Cov}(X, Y) = \frac{1}{n} \sum_{i=1}^{n} (X_i - \bar{X})(Y_i - \bar{Y})
\\]

In [ ]:
# Datos de ejemplo (4 muestras, 3 características)
X = np.array([[2.5, 2.4],
              [0.5, 0.7],
              [2.2, 2.9],
              [1.9, 2.2],
              [3.1, 3.0],
              [2.3, 2.7],
              [2, 1.6],
              [1, 1.1],
              [1.5, 1.6],
              [1.1, 0.9]])


# 2. Calcular la matriz de covarianza
cov_matrix = np.cov(X, rowvar=False)
cov_matrix

Cuando rowvar=False, significa que cada columna representa una variable y cada fila representa una observación (muestra o registro).

### Reshaping

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))
print("Array original:", arr)
print("Array reshapeado:\n", reshaped)

### Secuencias

In [ ]:
secuencia = np.arange(0, 10)
print(secuencia)

# Crear una secuencia con un paso de 2
secuencia_pasos = np.arange(0, 10, 2)
print(secuencia_pasos)

# Crear una secuencia de números
secuencia_flotante = np.arange(0, 5, 0.3333)
print(secuencia_flotante)

In [ ]:
# Crear una secuencia de 5 números equidistantes entre 0 y 10
secuencia = np.linspace(0, 10, 5)
print(secuencia)

### Operaciones con Arrays

#### Suma de una constante

In [ ]:
# Crear un array de 0 a 4
array = np.arange(5)

# Sumar 10 a cada elemento
suma_constante = array + 10
print(suma_constante)

#### Suma vectores

In [ ]:
# Crear dos arrays
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Sumar los arrays
suma_vectores = a + b
print(suma_vectores)

#### Multiplicación por una constante

In [ ]:
# Multiplicar el array por 3
multiplicacion_constante = a * 3
print(multiplicacion_constante)

#### Operaciones matriciales

\\[
\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
\times
\begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}
=
\begin{pmatrix}
(1 \cdot 5 + 2 \cdot 7) & (1 \cdot 6 + 2 \cdot 8) \\
(3 \cdot 5 + 4 \cdot 7) & (3 \cdot 6 + 4 \cdot 8)
\end{pmatrix}
=
\begin{pmatrix}
19 & 22 \\
43 & 50
\end{pmatrix}
\\]

In [ ]:
# Crear dos matrices
matriz_a = np.array([[1, 2], [3, 4]])
matriz_b = np.array([[5, 6], [7, 8]])

# Multiplicación de matrices (producto punto)
multiplicacion_matrices = np.dot(matriz_a, matriz_b)
print(multiplicacion_matrices)

### Ejercicio

Dado el siguiente conjunto de datos representado por dos matrices
𝐴
A y
𝐵
B, realiza las siguientes operaciones utilizando Numpy:



In [ ]:
import numpy as np
A = np.array([[4, 8, 12],
              [16, 20, 24],
              [28, 32, 36]])

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

#Suma de matrices
print("Suma de A y B:\n", A + B)
#Multiplicaicón de matrices
print("Multiplicación de A y B:\n", np.dot(A, B))
#Suma de una constante a una matriz
print("Sumar constante 10 a A: ", A + 10)

#Indexación

# Acceder a un elemento específico
print(A[[1, 2]])

# Modificar un elemento específico
A[[0,0]] = 100
print(A)

# Slicing
print("Submatriz 2x2 de A:\n", A[:2, :2])
print("Última columna de B:\n", B[:, -1])

# Creación de nuevas matrices
print("Matriz 4x4 de ceros:\n", np.zeros((4, 4)))
print("Matriz identidad 3x3:\n", np.eye(3))

# Multiplicación matricial
print("Producto matricial de A y B:\n", np.dot(A, B))



Suma de A y B:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
Multiplicación de A y B:
 [[120 144 168]
 [264 324 384]
 [408 504 600]]
Sumar constante 10 a A:  [[14 18 22]
 [26 30 34]
 [38 42 46]]
[[16 20 24]
 [28 32 36]]
[[100 100 100]
 [ 16  20  24]
 [ 28  32  36]]
Submatriz 2x2 de A:
 [[100 100]
 [ 16  20]]
Última columna de B:
 [3 6 9]
Matriz 4x4 de ceros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Matriz identidad 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Producto matricial de A y B:
 [[1200 1500 1800]
 [ 264  324  384]
 [ 408  504  600]]


* Suma de matrices: Suma las matrices A y B, y muestra el resultado.

* Multiplicación elemento a elemento: Multiplica A y B elemento a elemento.

* Suma de una constante: Suma el valor 10 a todos los elementos de la matriz A.

* Indexación:

   * Extrae el valor de la segunda fila y tercera columna de la matriz A.
   * Cambia el valor de la primera fila y primera columna de B a 100.

* Slicing:

   * Extrae la submatriz formada por las dos primeras filas y las dos primeras columnas de A.
   * Extrae la última columna de la matriz B.


* Creación de una nueva matriz:

  * Crea una matriz de 4x4 llena de ceros.
  *  Crea una matriz de identidad de tamaño 3x3.

* Multiplicación matricial: Calcula el producto matricial de A y B (utiliza la función np.dot).

